### ISSUE TITLE
Provide uninstall option or add uninstall instructions to README

### ISSUE THREAD

**Issue by urbenlegend** [nunodio/bitwig-fedora#1]
I'd like to see a easy uninstall option. This would be useful in removing Bitwig or cleanly updating Bitwig.

At the very least, some uninstall instructions in the README would be helpful for new users.

**Comment by nunodio** [comment]
Hello @urbenlegend,

Thank you for your feedback.
Next version will provide a uninstall mechanism. I'll keep this issue open until I release it.

**Comment by nunodio** [comment]
The uninstall feature has been implemented #3170dcf. This issue can now be closed.
